# Generated by Django 2.0.5 on 2018-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=550)),
                ('author', models.CharField(default='2', max_length=550)),
                ('img_url', models.CharField(default='3', max_length=550)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
