# Generated by Django 2.0.5 on 2018-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookList', '0002_remove_post_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_url',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
