# Generated by Django 2.0.5 on 2018-05-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookList', '0003_post_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='wxj', max_length=50),
        ),
    ]
